# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS EFS controller is a service controller for managing EFS resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Elastic File System (Amazon EFS)
description: |-
  Manage Amazon EFS resources in AWS from within your Kubernetes cluster.


  **About Amazon Elastic File System (Amazon EFS)**


  Amazon Elastic File System (Amazon EFS) provides serverless, fully elastic file storage so that you can share file data without provisioning or managing storage capacity and performance. 
  Amazon EFS is built to scale on demand to petabytes without disrupting applications, growing and shrinking automatically as you add and remove files. Because Amazon EFS has a simple web services interface, 
  you can create and configure file systems quickly and easily. The service manages all the file storage infrastructure for you, meaning that you can avoid the complexity of deploying, patching, 
  and maintaining complex file system configurations.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: AccessPoint
  spec: '{}'
- kind: FileSystem
  spec: '{}'
- kind: MountTarget
  spec: '{}'
maintainers:
- name: "efs maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon EFS Developer Resources
  url: https://aws.amazon.com/efs/resources/
